@ConcertTicketManagement_HostAddress = http://localhost:5158

GET {{ConcertTicketManagement_HostAddress}}/api/v1/events
Accept: application/json

###
# @name createevent
POST {{ConcertTicketManagement_HostAddress}}/api/v1/events
Content-Type: application/json 

{
  "eventDate": "2025-09-22",
  "eventTime": "17:00",
  "venue": "Lumen Field",
  "description": "ColdPlay concert"
}

###
# get events
GET {{ConcertTicketManagement_HostAddress}}/api/v1/events/{{createevent.response.body.$.id}}
Accept: application/json

###
# update event
PUT {{ConcertTicketManagement_HostAddress}}/api/v1/events/{{createevent.response.body.$.id}}
Content-Type: application/json 

{
  "eventDate": "2025-09-29",
  "eventTime": "19:00",
  "venue": "Lumen Field",
  "description": "ColdPlay concert"
}

###
# @name createevent
POST {{ConcertTicketManagement_HostAddress}}/api/v1/events
Content-Type: application/json 

{
  "eventDate": "2025-09-29",
  "eventTime": "19:00",
  "venue": "T Mobile Park",
  "description": "The Weekend concert"
}

###
# @name createevent
POST {{ConcertTicketManagement_HostAddress}}/api/v1/events
Content-Type: application/json 

{
  "eventDate": "2025-11-02",
  "eventTime": "21:00",
  "venue": "Lumen Field",
  "description": "Taylor Swift tour"
}

###
# @name createevent
POST {{ConcertTicketManagement_HostAddress}}/api/v1/events
Content-Type: application/json 

{
  "eventDate": "2025-09-22",
  "eventTime": "17:00",
  "venue": "Lumen Field",
  "description": "ColdPlay concert"
}

###
# @name createevent
POST {{ConcertTicketManagement_HostAddress}}/api/v1/events
Content-Type: application/json 

{
  "eventDate": "2025-12-10",
  "eventTime": "21:00",
  "venue": "Climate Pledge Arena ",
  "description": "Sting concert"
}

###
# @name createtickets
POST {{ConcertTicketManagement_HostAddress}}/api/v1/events/{{createevent.response.body.$.id}}/settickets
Content-Type: application/json 

[
  {
    "seatLocation": {
      "section": "221",
      "row": "15",
      "seatNumber": 10
    },
    "price": 120,
    "type": 0
  },
  {
    "seatLocation": {
      "section": "221",
      "row": "15",
      "seatNumber": 11
    },
    "price": 120,
    "type": 0
  },
  {
    "seatLocation": {
      "section": "221",
      "row": "15",
      "seatNumber": 12
    },
    "price": 110,
    "type": 0
  }
]

###

# @name geteventtickets
GET {{ConcertTicketManagement_HostAddress}}/api/v1/tickets/{{createevent.response.body.$.id}}

###

# Reserve a ticket
POST {{ConcertTicketManagement_HostAddress}}/api/v1/tickets/{{geteventtickets.response.body.$.items[0].id}}/events/{{createevent.response.body.$.id}}/reservation

###


# Cancel ticket reservation
DELETE {{ConcertTicketManagement_HostAddress}}/api/v1/tickets/reservation

###

###
# @name blocktickets
PATCH {{ConcertTicketManagement_HostAddress}}/api/v1/events/{{createevent.response.body.$.id}}/blocktickets
Content-Type: application/json 

[
  "{{geteventtickets.response.body.$.items[0].id}}",
  "{{geteventtickets.response.body.$.items[1].id}}"
]

###
# @name unblocktickets
PATCH {{ConcertTicketManagement_HostAddress}}/api/v1/events/{{createevent.response.body.$.id}}/unblocktickets
Content-Type: application/json 

[
  "{{geteventtickets.response.body.$.items[0].id}}",
  "{{geteventtickets.response.body.$.items[1].id}}"
]

###

# @name purchasetickets
POST {{ConcertTicketManagement_HostAddress}}/api/v1/tickets/purchase
Content-Type: application/json 

{
  "cardNumber": "1234-1234",
  "cardHolderName": "John Doe",
  "expirationDate": "07/2025",
  "cvv": "123",
  "billingAddress": "12 Main St"
}

###
